services:
  - type: web
    name: rag-project-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: LANGFUSE_PUBLIC_KEY
        sync: false
      - key: LANGFUSE_SECRET_KEY
        sync: false
      - key: LANGFUSE_HOST
        value: https://cloud.langfuse.com
      - key: ENABLE_RERANKER
        value: "false"
      - key: EMBEDDING_MODEL
        value: models/gemini-embedding-001
      - key: LLM_MODEL
        value: gemini-2.5-flash
      - key: TOP_K_RETRIEVAL
        value: 20
      - key: TOP_K_RERANK
        value: 5
      - key: CHUNK_SIZE
        value: 512
      - key: CHUNK_OVERLAP
        value: 64
